services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kartvizit-backend
    ports:
      - "127.0.0.1:5002:5002"
    volumes:
      - media_data:/app/media
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kartvizit-frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  media_data:
