"""Add appointments table

Revision ID: e6b045bf8552
Revises: 
Create Date: 2025-09-23 11:44:13.303907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b045bf8552'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=150), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('full_name', sa.Unicode(length=255), nullable=True),
    sa.Column('role', sa.Unicode(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('url', sa.Unicode(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.Unicode(length=255), nullable=True),
    sa.Column('company_type', sa.Unicode(length=100), nullable=True),
    sa.Column('tax_office', sa.Unicode(length=100), nullable=True),
    sa.Column('tax_number', sa.Unicode(length=50), nullable=True),
    sa.Column('trade_registry_number', sa.Unicode(length=50), nullable=True),
    sa.Column('mersis_no', sa.Unicode(length=50), nullable=True),
    sa.Column('phone', sa.Unicode(length=50), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('website', sa.Unicode(length=500), nullable=True),
    sa.Column('address', sa.Unicode(length=500), nullable=True),
    sa.Column('district', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=True),
    sa.Column('country', sa.Unicode(length=100), nullable=True),
    sa.Column('postal_code', sa.Unicode(length=20), nullable=True),
    sa.Column('phone_alt', sa.Unicode(length=50), nullable=True),
    sa.Column('email_alt', sa.Unicode(length=255), nullable=True),
    sa.Column('website_alt', sa.Unicode(length=500), nullable=True),
    sa.Column('billing_address', sa.Unicode(length=500), nullable=True),
    sa.Column('description', sa.Unicode(length=1000), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Unicode(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('last_visited_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.Unicode(length=50), nullable=True),
    sa.Column('website', sa.Unicode(length=500), nullable=True),
    sa.Column('address', sa.Unicode(length=500), nullable=True),
    sa.Column('about', sa.Unicode(length=1000), nullable=True),
    sa.Column('photo_url', sa.Unicode(length=500), nullable=True),
    sa.Column('video_url', sa.Unicode(length=500), nullable=True),
    sa.Column('company', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('gender', sa.Unicode(length=50), nullable=True),
    sa.Column('card_name', sa.Unicode(length=255), nullable=True),
    sa.Column('theme', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('marketplaces', sa.JSON(), nullable=True),
    sa.Column('account_numbers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('companies')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
